### ISSUE TITLE
About the Figure 14 in the paper

### ISSUE THREAD

**Issue by MAX-OTW** [vignywang/AWDesc#1]
Hello, @vignywang -I really appreciate for your work！Congratulations :)
The Figure 14(attention maps) in the paper looks great. Currently I want to try to implement it but I failed. Is it convenient to provide the relevant implementation code?Of course, detailed guidance would be better.
I am always looking forward to your kind response.
Best regards.

**Comment by vignywang** [comment]
Thank you for your interest. The full training and visualization code will be released within a month.
