### ISSUE TITLE
Is heatmap4 = self.heatmap3(c4) a typo?

### ISSUE THREAD

**Issue by Shiaoming** [vignywang/AWDesc#2]
Should it be `heatmap4 = self.heatmap4(c4)` ?

ref: https://github.com/vignywang/AWDesc/blob/711d68395ad7a9557fe93725fbf4566f4ac2fa55/nets/network.py#LL77C31-L77C31

**Comment by vignywang** [comment]
Thank you for your reminder and contribution. We will correct this error.
