### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by LooperzZ** [vignywang/AWDesc#4]
Hello, this is a great job, how is the dataset in your project made?what method is used to select the corresponding images?and what algorithm extracts keypoints and despoints?Can this part of the code work be made public?

**Comment by vignywang** [comment]
The dataset is based on a modification of the D2Net code for processing Megadeth [https://github.com/mihaidusmanu/d2-net/tree/master/megadepth_utils]. Keypoint supervision is similar to superpoint, using points that should be consistent after change alone, this part of the code refers to [https://github.com/rpautrat/SuperPoint]. For sampling points of the descriptor, we select the local extreme points in the heat map, and then construct the correspondence point pairs by the true correspondence.

**Comment by LooperzZ** [comment]
What SOTA algorithm is used to extract the description of the descriptor used to supervise the training? Can you tell me that you want to make your own dataset according to your specifications.
